src/Entity/CartItem.php
<?php

namespace App\Entity;

use App\Repository\CartItemRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CartItemRepository::class)]
class CartItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'cartItems')]
    private ?Product $product = null;

    #[ORM\Column]
    private ?int $Quantity = null;

    #[ORM\ManyToOne(inversedBy: 'cartItems')]
    private ?Cart $cart = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        $this->cart = $cart;

        return $this;
    }
}

src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\CommandRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandRepository::class)]
class Command
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'commands')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\OneToMany(mappedBy: 'command', targetEntity: CommandItem::class, cascade: ["persist"], orphanRemoval: true)]
    private Collection $commandItems;

    public function __construct()
    {
        $this->commandItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, CommandItem>
     */
    public function getCommandItems(): Collection
    {
        return $this->commandItems;
    }

    public function addCommandItem(CommandItem $commandItem): self
    {
        if (!$this->commandItems->contains($commandItem)) {
            $this->commandItems->add($commandItem);
            $commandItem->setCommand($this);
        }

        return $this;
    }

    public function removeCommandItem(CommandItem $commandItem): self
    {
        if ($this->commandItems->removeElement($commandItem)) {
            if ($commandItem->getCommand() === $this) {
                $commandItem->setCommand(null);
            }
        }

        return $this;
    }
}

src/Controller/CommandController.php
<?php

namespace App\Controller;

use App\Entity\Command;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

class CommandController extends AbstractController
{
    #[Route('/commands', name: 'commands')]
    public function index(UserInterface $user)
    {
        $commands = $user->getCommands();

        return $this->render('commands/index.html.twig', [
            'commands' => $commands,
        ]);
    }

    #[Route('/commands/{id}', name: 'commands_show')]
    public function show(Command $command): Response
    {
        $access = $command->getUser() === $this->getUser();
        if(!$access){
            return $this->render("home/index.html.twig");
        }

        return $this->render('commands/show.html.twig', [
            'command' => $command,
        ]);
    }
}

templates/commands/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ encore_entry_link_tags('bootstrap') }}
    {{ encore_entry_link_tags('styles') }}
    {# {{ encore_entry_link_tags('command') }} #}
{% endblock %}

{% block title %}Mes commandes{% endblock %}

{% block body %}
<section class="container">
    <h1 class="my-4 text-center">Mes commandes</h1>

    <table class="table table-striped">
        <thead class="bg-light text-dark">
            <tr class="text-center">
                <th>Commande ID</th>
                <th>Status</th>
                <th>Date de création</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for command in commands %}
            <tr class="text-center text-dark">
                <td>{{ command.id }}</td>
                <td>
                    <span class="badge text-dark badge-{{ command.status == 'Payer' ? 'success' : 'danger' }}">
                        {{ command.status }}
                    </span>
                </td>
                <td>{{ command.createdAt|date('Y-m-d H:i') }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('commands_show', {id: command.id}) }}">Détails</a>
                </td>
            </tr>
            {% else %}
            <tr>
                <td colspan="3" class="text-center">
                    <p class="lead text-dark">Aucune commande trouvée</p>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock %}

templates/commands/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Command Details{% endblock %}

{% block body %}
<section class="container">
    <section class="row justify-content-center">
        <article class="col-md-8">
            <article class="card">
                <header class="card-header">
                    <h1>Detail de votre commande</h1>
                </header>
                <section class="card-body">
                    <p><strong>Commandé le :</strong> {{ command.createdAt|date('Y-m-d H:i') }}</p>
                    <p><strong>Status :</strong> {{ command.status }}</p>

                    <h2>Items:</h2>
                    
                    <ul class="list-group">
                        {% for commandItem in command.commandItems %}
                        <li class="list-group-item">
                            <strong>Produit :</strong> {{ commandItem.product.name }} <br>
                            <strong>Quantité :</strong> {{ commandItem.quantity }}
                        </li>
                        {% endfor %}
                    </ul>
                </section>
            </article>
        </article>
    </section>
</section>
{% endblock %}